package us.chouser.cubbystream;

import android.os.Handler;
import android.os.Looper;
import java.util.Locale;

/**
 * Generated by train_detect.clj — do not edit by hand.
 */
public class GeneratedDetector implements AdDetector {

    public static final String ALGORITHM_KEY = "generated";

    private static final int FRAME_SIZE     = AudioTap.FRAME_SIZE;
    private static final int TRIGGER_FRAMES = 25;

    // ---- DSP buffers ----
    private final float[] monoBuf = new float[FRAME_SIZE];
    private final float[] re      = new float[FRAME_SIZE];
    private final float[] im      = new float[FRAME_SIZE];
    private final float[] prevMag = new float[FRAME_SIZE / 2];

    // ---- Feature state ----
    private final AudioFrameUtils.RollingStats energyRoll = new AudioFrameUtils.RollingStats(8);

    // ---- Detection state ----
    private int     belowCount  = 0;
    private int     aboveCount  = 0;
    private boolean inAdBreak   = false;
    private volatile float latestSignal = Float.NaN;

    private AdDetector.Listener listener;
    private final Handler mainHandler = new Handler(Looper.getMainLooper());

    @Override public String  getDisplayName()  { return "Generated Tree"; }
    @Override public String  getAlgorithmKey() { return ALGORITHM_KEY; }
    @Override public boolean hasThreshold()    { return false; }
    @Override public float   getThreshold()    { return Float.NaN; }
    @Override public float   getSignalLevel()  { return latestSignal; }
    @Override public String  getStatusText() {
        float s = latestSignal;
        if (Float.isNaN(s)) return null;
        return String.format(Locale.US, "%s (%.0f%%)", s >= 0.5f ? "game" : "ads", s * 100f);
    }

    @Override public void    setListener(AdDetector.Listener l) { this.listener = l; }
    @Override public boolean isInAdBreak()   { return inAdBreak; }
    @Override public void    resetCounters() { belowCount = 0; aboveCount = 0; }
    @Override public void    reset() {
        belowCount = aboveCount = 0; inAdBreak = false; latestSignal = Float.NaN;
    }

    @Override
    public void onAudioFrame(float[] samples, int frameSize, int channelCount, int sampleRate) {
        AudioFrameUtils.toMono(samples, frameSize, channelCount, monoBuf);
        AudioFrameUtils.hannWindow(monoBuf, re, im, FRAME_SIZE);
        AudioFrameUtils.fft(re, im, FRAME_SIZE);
        float midE = AudioFrameUtils.bandEnergy(re, im, 120, 1800, sampleRate, FRAME_SIZE);
        float highE = AudioFrameUtils.bandEnergy(re, im, 1800, 8000, sampleRate, FRAME_SIZE);
        AudioFrameUtils.SpectralStats ss = AudioFrameUtils.spectralStats(re, im, prevMag, FRAME_SIZE);
        energyRoll.push(midE);
        if (!(energyRoll.ready())) return;
        latestSignal = (float) predict(energyRoll.std(), energyRoll.mean(), AudioFrameUtils.midHighRatio(midE, highE), AudioFrameUtils.fluxEnergyRatio(ss.flux, midE));
        updateStateMachine(latestSignal);
    }

    private static double predict(double energy_std, double energy_mean, double mid_high_ratio, double flux_energy_ratio) {
    if (energy_std <= 7.811619) {
      return 0; // ADS
    } else {
      if (energy_mean <= 247.907581) {
        return 0; // ADS
      } else {
        if (energy_std <= 13.534203) {
          if (mid_high_ratio <= 0.141425) {
            return 1; // GAME
          } else {
            if (flux_energy_ratio <= 10.594752) {
              return 0; // ADS
            } else {
              if (flux_energy_ratio <= 11.058510) {
                return 1; // GAME
              } else {
                return 0; // ADS
              }
            }
          }
        } else {
          if (energy_mean <= 248.350225) {
            return 1; // GAME
          } else {
            if (energy_mean <= 343.512263) {
              if (energy_mean <= 326.370663) {
                return 0; // ADS
              } else {
                if (energy_mean <= 328.625250) {
                  return 1; // GAME
                } else {
                  if (flux_energy_ratio <= 13.704030) {
                    if (energy_mean <= 341.915344) {
                      if (mid_high_ratio <= 0.782231) {
                        return 1; // GAME
                      } else {
                        if (flux_energy_ratio <= 0.008212) {
                          return 1; // GAME
                        } else {
                          if (energy_std <= 16.812706) {
                            return 0; // ADS
                          } else {
                            if (energy_std <= 16.927075) {
                              return 1; // GAME
                            } else {
                              if (energy_mean <= 335.270162) {
                                if (energy_std <= 26.046157) {
                                  return 1; // GAME
                                } else {
                                  if (energy_mean <= 329.358906) {
                                    if (energy_mean <= 328.748863) {
                                      return 0; // ADS
                                    } else {
                                      return 1; // GAME
                                    }
                                  } else {
                                    return 0; // ADS
                                  }
                                }
                              } else {
                                if (mid_high_ratio <= 3.256177) {
                                  return 0; // ADS
                                } else {
                                  if (energy_mean <= 338.675194) {
                                    return 0; // ADS
                                  } else {
                                    return 1; // GAME
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      return 1; // GAME
                    }
                  } else {
                    if (energy_mean <= 330.302894) {
                      return 0; // ADS
                    } else {
                      return 1; // GAME
                    }
                  }
                }
              }
            } else {
              return 0; // ADS
            }
          }
        }
      }
    }
    }

    private void updateStateMachine(float signal) {
        // predict() returns 1=GAME, 0=ADS
        if (signal > 0.5f) {
            aboveCount = 0; belowCount++;
            if (inAdBreak && belowCount >= TRIGGER_FRAMES) {
                inAdBreak = false;
                mainHandler.post(() -> { if (listener != null) listener.onGameResumed(); });
            }
        } else {
            belowCount = 0; aboveCount++;
            if (!inAdBreak && aboveCount >= TRIGGER_FRAMES) {
                inAdBreak = true;
                mainHandler.post(() -> { if (listener != null) listener.onAdBreakStarted(); });
            }
        }
    }
}
